#define WIFI_SSID "YOUR_WIFI_NETWORK_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD_HERE"

#define FIREBASE_API_KEY "YOUR_FIREBASE_API_KEY" 
#define FIREBASE_HOST "YOUR-PROJECT-ID.firebaseio.com"

#define CANVAS_APP_ID "default-app-id"